import { Product } from "../types/product";

export const products: Product[] = [
    {
        id: "p1",
        name: "Producto 1",
        description: "Descripción corta del producto 1",
        price: 1999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    }, {
        id: "p2",
        name: "Producto 2",
        description: "Descripción corta del producto 2",
        price: 2999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p3",
        name: "Producto 3",
        description: "Descripción corta del producto 3",
        price: 3999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p4",
        name: "Producto 4",
        description: "Descripción corta del producto 4",
        price: 4999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p5",
        name: "Producto 5",
        description: "Descripción corta del producto 5",
        price: 5999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p6",
        name: "Producto 6",
        description: "Descripción corta del producto 6",
        price: 6999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p7",
        name: "Producto 7",
        description: "Descripción corta del producto 7",
        price: 7999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p8",
        name: "Producto 8",
        description: "Descripción corta del producto 8",
        price: 8999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
    {
        id: "p9",
        name: "Producto 9",
        description: "Descripción corta del producto 9",
        price: 9999,
        image: "/Icon.png",
        tags: ["más vendido"],
        category: "Ropita",
    },
];